fixtures:
  forge_modules:
    stdlib:
      repo: 'puppetlabs-stdlib'
      ref:  '4.16.0'
    apache:
      repo: 'puppetlabs-apache'
      ref:  '1.11.0'
    concat:
      repo: 'puppetlabs-concat'
      ref:  '2.2.0'
    vcsrepo:
      repo: 'puppetlabs-vcsrepo'
      ref:  '1.5.0'
    postgresql:
      repo: 'puppetlabs-postgresql'
      ref:  '4.9.0'
    ruby:
      repo: 'puppetlabs-ruby'
      ref:  '0.6.0'
    git:
      repo: 'Aethylred-git'
      ref:  '0.3.1'
    redis:
      repo: 'thomasvandoren-redis'
      ref:  '0.10.0'
    wget:
      repo: 'maestrodev-wget'
      ref:  '1.7.3'
    gcc:
      repo: 'puppetlabs-gcc'
      ref:  '0.3.0'
  symlinks:
    gitlab: "#{source_dir}"
