fixtures:
  forge_modules:
    stdlib:
      repo: 'puppetlabs-stdlib'
      ref:  '4.2.2'
    apache:
      repo: 'puppetlabs-apache'
      ref:  '1.0.1'
    concat:
      repo: 'puppetlabs-concat'
      ref:  '1.1.0'
    vcsrepo:
      repo: 'puppetlabs-vcsrepo'
      ref:  '1.0.2'
    postgresql:
      repo: 'puppetlabs-postgresql'
      ref:  '3.3.3'
    git:
      repo: 'Aethylred-git'
      ref:  '0.1.2'
    redis:
      repo: 'thomasvandoren-redis'
      ref:  '0.10.0'
    wget:
      repo: 'maestrodev-wget'
      ref:  '1.5.3'
    gcc:
      repo: 'puppetlabs-gcc'
      ref:  '0.2.0'
  repositories:
    ruby:
      repo: 'https://github.com/puppetlabs/puppetlabs-ruby.git'
      ref:  'origin/master'
  symlinks:
    gitlab: "#{source_dir}"
