fixtures:
  forge_modules:
    stdlib:
      repo: 'puppetlabs-stdlib'
      ref:  '4.3.2'
    # apache:
    #   repo: 'puppetlabs-apache'
    #   ref:  '1.1.1'
    concat:
      repo: 'puppetlabs-concat'
      ref:  '1.1.0'
    vcsrepo:
      repo: 'puppetlabs-vcsrepo'
      ref:  '1.1.0'
    postgresql:
      repo: 'puppetlabs-postgresql'
      ref:  '3.4.2'
    ruby:
      repo: 'puppetlabs-ruby'
      ref:  '0.3.0'
    git:
      repo: 'Aethylred-git'
      ref:  '0.3.1'
    redis:
      repo: 'thomasvandoren-redis'
      ref:  '0.10.0'
    wget:
      repo: 'maestrodev-wget'
      ref:  '1.5.6'
    gcc:
      repo: 'puppetlabs-gcc'
      ref:  '0.2.0'
  repositories:
    apache:
      repo: 'https://github.com/puppetlabs/puppetlabs-apache.git'
      ref: 'origin/master'
  symlinks:
    gitlab: "#{source_dir}"
