forge 'https://forgeapi.puppetlabs.com'

mod 'puppetlabs-stdlib'
mod 'puppetlabs-apt'
mod 'puppetlabs-vcsrepo'
mod 'puppetlabs-apache'
mod 'puppetlabs-postgresql'
mod 'Aethylred-git'
mod 'arioch-redis'
mod 'puppetlabs-ruby'
mod 'puppet-nodejs'
mod 'stahnma-epel'